### ISSUE TITLE
Plugin serverservice code mismatch with the docs

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse/che-archetypes#39]
Seems like serverservice is supposed to be deployed on ws-master as these docs say
https://www.eclipse.org/che/docs/plugins/serverworkspace-access/index.html

However, orginal sample code contains code that presumes it has to be run on ws-agent:
https://github.com/eclipse/che-archetypes/blob/master/plugin-serverservice-archetype/src/main/resources/archetype-resources/plugins/__rootArtifactId__/__rootArtifactId__-ide/src/main/java/__packageInPathFormat__/ide/MyServiceClient.java#L60

Needs either to change the docs, or edit the sample

**Comment by TylerJewell** [comment]
The idea in the docs is that there should be an example of master, agent and ide.  So one of each.

**Comment by mkuznyetsov** [comment]
@TylerJewell so I'll make this one as a ws-master service sample.
Then JSON sample will be used as ws-agent service sample.
And what do you mean by 'ide'?

**Comment by TylerJewell** [comment]
An ide example is what we do with the menu / action.  It is an extension for the ide itself.

**Comment by skabashnyuk** [comment]
- sample-plugin-menu - is IDE sample
- sample-plugin-serverservice - ws master rest service
- sample-plugin-json - https://github.com/eclipse/che-archetypes/issues/29 ws-agent rest service.

I think the confusion was because sample-plugin-serverservice has issues in code and point to wrong api endpoint(agent instead of master).
